package org.example.taxi.service.cache; // New package for cache-related DTOs

import lombok.Data;
import org.example.taxi.entity.User;

import java.time.LocalDateTime;

@Data
public class RegistrationCacheEntry {
    private String sessionId;         // Unique ID generated by AuthController
    private User.UserType userType;   // CLIENT or DRIVER, set by the deep link
    private Long chatId;              // Telegram chatId, set when bot is started with this session ID
    private String phoneNumber;       // User's phone number, either from Telegram profile or shared
    private String generatedPassword; // The *plaintext* password generated by the bot, held briefly
    private LocalDateTime createdAt;
    private LocalDateTime expiresAt;  // For session expiration (e.g., 10 minutes)

    public boolean isExpired() {
        return expiresAt != null && LocalDateTime.now().isAfter(expiresAt);
    }
}